services:
  misterx:
    image: lausi95/misterx-backend
    networks: [traefik]
    environment:
      - SPRING_DATA_MONGODB_HOST=misterx-database
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.misterx.rule=Host(`misterx.lausi95.net`)
      - traefik.http.routers.misterx.entrypoints=websecure
      - traefik.http.routers.misterx.tls.certresolver=letsencrypt

  misterx-database:
    image: mongo
    networks: [traefik]
    volumes: [misterx2025-mongodb:/etc/mongodb]
    restart: unless-stopped

networks:
  traefik:
    external: true
    name: traefik

volumes:
  misterx2025-mongodb:
