name: Deployment Pipeline [Production]
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE: lausi95/misterx-backend:latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_IMAGE .
      - run: docker push $DOCKER_IMAGE

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://tennislichtenberg.de
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/id_rsa
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 lausi95.net >> /home/runner/.ssh/known_hosts
      - name: Run ansible script
        shell: bash
        run: |
          service ssh status
          cd ansible
          cat deploy-prod.yml
          ansible-playbook -vvv -e "ansible_user=tom" --private-key /home/runner/.ssh/id_rsa -i hosts.yml deploy-prod.yml